install.packages('shiny')
install.packages('shinythemes')

install.packages('shinyWidgets')
install.packages('ggplot2') #Grammar of graphics
install.packages('ggfortify')
install.packages('car')
install.packages('shinysky')
install.packages('rhandsontable')
install.packages('writexl')
install.packages('shinyjs')
install.packages('png')
install.packages('knitr')
install.packages('htmlwidgets')
install.packages("shinycssloaders")
